name: Rebase Upstream

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: pull current repo
        uses: actions/checkout@v2
        with:
          path: self
      - name: pull source repo
        uses: actions/checkout@v2
        with:
          repository: JACKUSR2089/v2ray-subscribed
          ref: master
          fetch-depth: '0'
          path: target
      - name: configure git
        run: |
          git config --global user.email "user@example.com"
          git config --global user.name "GitHub Actions Bot"
      - name: update file content
        run: |
          echo "**********************************"
          latest=$(git ls-tree -r --name-only HEAD . | \
              while read filename; do echo "$(git log -1 --format="%at" -- $filename) $filename"; done | \
              sort -k1n | tail -n1 | cut -d' ' -f2-)
          last="../self/subscribed/last"
          echo "Found latest file ${latest}"
          if diff -q --from-file $last $latest; then
              echo "not change"
          else
              echo "changed"
              cat $latest > $last
              echo "updated ${last} based on ${latest}"
          fi
        working-directory: target
      - name: push to repo
        run: |
            git add subscribed/last
            if git commit -m 'auto-update on '"$(date)"; then
              git push
            fi
        working-directory: self
