name: Rebase Upstream

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: self
      - uses: actions/checkout@v2
        with:
          repository: JACKUSR2089/v2ray-subscribed
          ref: master
          path: target
      - run: |
          git config --global user.email "user@example.com"
          git config --global user.name "GitHub Actions Bot"
      - run: |
          echo "**********************************"
          git ls-tree -r --name-only HEAD subscribed | while read filename; \
            do echo "$(git log -1 --format="%ad" -- $filename) $filename";
          latest=$(git ls-tree -r --name-only HEAD subscribed | while read filename; \
            do echo "$(git log -1 --format="%ad" -- $filename) $filename"; done | \
            sort -k2M -k3n -k4 | tail -n1 | cut  -d' ' -f7-)
          last="../self/subscribed/last"
          echo "Found latest file ${latest}"
          if diff -q --from-file $last $latest; then
              echo "not change"
          else
              echo "changed"
              cat $latest > $last
              echo "updated ${last} based on ${latest}"
          fi
        working-directory: target
      - run: |
            git add subscribed/last
            git commit -m 'auto-update on '"$(date)"
            git push
        working-directory: self
