# This is a basic workflow to help you get started with Actions

name: vv

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: srt32/git-actions@v0.0.3

      # Runs a single command using the runners shell
      - name: Run a multi-line script
        run: |
          #git config --global hyrgg
          #https://github.com/JACKUSR2089/v2ray-subscribed
          git remote add upstream https://github.com/JACKUSR2089/v2ray-subscribed
          git fetch upstream
          git rebase upstream/master
          #if git pull origin;
          #then 
          #    echo "**********************************"
          #    echo "repository updated"
          #else
          #    echo "**********************************"
          #    echo "repository not change"
          #fi
          echo "**********************************"
          name=$(ls ../../subscribed/ -t | head -n 1)
          latest="../../subscribed/${name}"
          last="../../subscribed/last"
          echo $latest
          echo $last
          #echo $(diff -q --from-file $last $latest; echo $?)
          if diff -q --from-file $last $latest;
              then
              echo "not change"
          else
              echo "changed"
               cat $latest > $last
              echo "update to last"
          fi
