name: Rebase Upstream
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git remote add upstream https://github.com/JACKUSR2089/v2ray-subscribed
      - run: git fetch upstream
      - run: |
          git config --global user.email "user@example.com"
          git config --global user.name "GitHub Actions Bot"
      - run: git rebase upstream/master
      - run: |
          echo "**********************************"
          name=$(ls subscribed/ -t | head -n 1)
          latest="subscribed/${name}"
          last="subscribed/last"
          echo $latest
          echo $last
          #echo $(diff -q --from-file $last $latest; echo $?)
          if diff -q --from-file $last $latest;
              then
              echo "not change"
          else
              echo "changed"
              cat $latest > $last
              echo "update to last"
          fi
      - run: git push
